ci: temporary off lint and test jobs

diff --git a/.github/workflows/ci-pr-to-develop.yml b/.github/workflows/ci-pr-to-develop.yml
--- a/.github/workflows/ci-pr-to-develop.yml
+++ b/.github/workflows/ci-pr-to-develop.yml
@@ -11,164 +11,164 @@ permissions:
   pull-requests: write
 
 jobs:
-  run-lint:
-    name: Run ESLint
-    runs-on: 'ubuntu-latest'
+  # run-lint:
+  #   name: Run ESLint
+  #   runs-on: 'ubuntu-latest'
 
-    strategy:
-      matrix:
-        node-version: ['22']
+  #   strategy:
+  #     matrix:
+  #       node-version: ['22']
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Set up Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.node-version }}
-          cache: 'npm'
+  #     - name: Set up Node.js ${{ matrix.node-version }}
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: ${{ matrix.node-version }}
+  #         cache: 'npm'
 
-      - name: Install dependencies
-        run: npm ci
+  #     - name: Install dependencies
+  #       run: npm ci
 
-      - name: Run ESLint
-        shell: bash
-        run: |
-          set +e
-          npm run lint > full-lint.log 2>&1
-          exit_code="${PIPESTATUS[0]}"
-          set -e
+  #     - name: Run ESLint
+  #       shell: bash
+  #       run: |
+  #         set +e
+  #         npm run lint > full-lint.log 2>&1
+  #         exit_code="${PIPESTATUS[0]}"
+  #         set -e
 
-          SUMMARY_FILE="summary-lint-errors.log"
-          grep -B 1 -E '\[warn\]|Error:|Warning:' full-lint.log > "$SUMMARY_FILE" || true
+  #         SUMMARY_FILE="summary-lint-errors.log"
+  #         grep -B 1 -E '\[warn\]|Error:|Warning:' full-lint.log > "$SUMMARY_FILE" || true
 
-          if [ ! -s "$SUMMARY_FILE" ]; then
-            echo "✅ No lint errors found." > "$SUMMARY_FILE"
-          fi
+  #         if [ ! -s "$SUMMARY_FILE" ]; then
+  #           echo "✅ No lint errors found." > "$SUMMARY_FILE"
+  #         fi
 
-          if [ "$exit_code" -ne 0 ]; then
-            echo "❌ ESLint errors found."
-          else
-            echo "✅ No lint errors."
-          fi
+  #         if [ "$exit_code" -ne 0 ]; then
+  #           echo "❌ ESLint errors found."
+  #         else
+  #           echo "✅ No lint errors."
+  #         fi
 
-          exit "$exit_code"
+  #         exit "$exit_code"
 
-      - name: Upload lint logs
-        uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: lint-results
-          path: |
-            full-lint.log
-            summary-lint-errors.log
+  #     - name: Upload lint logs
+  #       uses: actions/upload-artifact@v4
+  #       if: always()
+  #       with:
+  #         name: lint-results
+  #         path: |
+  #           full-lint.log
+  #           summary-lint-errors.log
 
-  run-tests:
-    name: Run Tests
-    runs-on: 'ubuntu-latest'
-    needs: [ 'run-lint' ]
+  # run-tests:
+  #   name: Run Tests
+  #   runs-on: 'ubuntu-latest'
+  #   needs: [ 'run-lint' ]
 
-    strategy:
-      matrix:
-        node-version: ['22']
-        mongodb-version: ['8.0']
-      max-parallel: 1
+  #   strategy:
+  #     matrix:
+  #       node-version: ['22']
+  #       mongodb-version: ['8.0']
+  #     max-parallel: 1
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Install Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.node-version }}
-          cache: 'npm'
+  #     - name: Install Node.js ${{ matrix.node-version }}
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: ${{ matrix.node-version }}
+  #         cache: 'npm'
 
-      - name: Install MongoDB ${{ matrix.mongodb-version }}
-        uses: supercharge/mongodb-github-action@1.12.0
-        with:
-          mongodb-version: ${{ matrix.mongodb-version }}
-          mongodb-db: ${{ secrets.MONGO_DB }}
-          mongodb-username: ${{ secrets.MONGO_USERNAME }}
-          mongodb-password: ${{ secrets.MONGO_PASSWORD }}
+  #     - name: Install MongoDB ${{ matrix.mongodb-version }}
+  #       uses: supercharge/mongodb-github-action@1.12.0
+  #       with:
+  #         mongodb-version: ${{ matrix.mongodb-version }}
+  #         mongodb-db: ${{ secrets.MONGO_DB }}
+  #         mongodb-username: ${{ secrets.MONGO_USERNAME }}
+  #         mongodb-password: ${{ secrets.MONGO_PASSWORD }}
 
-      - name: Install MongoDB shell
-        run: |
-          sudo apt-get install -y gnupg curl
-          curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
-          sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg \
-          --dearmor
-          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/8.0 multiverse" | \
-          sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
-          sudo apt-get update && sudo apt-get install -y mongodb-mongosh
+  #     - name: Install MongoDB shell
+  #       run: |
+  #         sudo apt-get install -y gnupg curl
+  #         curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
+  #         sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg \
+  #         --dearmor
+  #         echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/8.0 multiverse" | \
+  #         sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
+  #         sudo apt-get update && sudo apt-get install -y mongodb-mongosh
 
-      - name: Check MongoDB
-        run: |
-          for i in {1..30}; do
-            mongosh --eval "db.runCommand({ ping: 1 })" localhost:27017 && echo "MongoDB is up (attempt $i)" && exit 0
-            echo "Waiting for MongoDB... (attempt $i)"
-            sleep 2
-          done
-          echo "MongoDB did not start in time!" && exit 1
+  #     - name: Check MongoDB
+  #       run: |
+  #         for i in {1..30}; do
+  #           mongosh --eval "db.runCommand({ ping: 1 })" localhost:27017 && echo "MongoDB is up (attempt $i)" && exit 0
+  #           echo "Waiting for MongoDB... (attempt $i)"
+  #           sleep 2
+  #         done
+  #         echo "MongoDB did not start in time!" && exit 1
 
-      - name: Install dependencies
-        run: npm ci
+  #     - name: Install dependencies
+  #       run: npm ci
 
-      - name: Run Tests and generate logs
-        env:
-          NODE_OPTIONS: --max_old_space_size=4096
-          MONGO_DB: ${{ secrets.MONGO_DB }}
-          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
-          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
-          MONGO_HOST: ${{ secrets.MONGO_HOST }}
-          MONGO_PORT: ${{ secrets.MONGO_PORT }}
-        run: |
-          echo "🚀 Run Tests..."
+  #     - name: Run Tests and generate logs
+  #       env:
+  #         NODE_OPTIONS: --max_old_space_size=4096
+  #         MONGO_DB: ${{ secrets.MONGO_DB }}
+  #         MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
+  #         MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
+  #         MONGO_HOST: ${{ secrets.MONGO_HOST }}
+  #         MONGO_PORT: ${{ secrets.MONGO_PORT }}
+  #       run: |
+  #         echo "🚀 Run Tests..."
 
-          npm run test -- --ci 2>&1 | tee "full-tests-results-${{ matrix.node-version }}.log"
+  #         npm run test -- --ci 2>&1 | tee "full-tests-results-${{ matrix.node-version }}.log"
 
-          exit_code="${PIPESTATUS[0]}"
-          SUMMARY_ERRORS_FILE="summary-tests-errors-${{ matrix.node-version }}.log"
+  #         exit_code="${PIPESTATUS[0]}"
+  #         SUMMARY_ERRORS_FILE="summary-tests-errors-${{ matrix.node-version }}.log"
 
-          grep -E "Test Suites:|Tests:|Snapshots:|Time:" "full-tests-results-${{ matrix.node-version }}.log" > \
-            summary-tests-results-${{ matrix.node-version }}.log || \
-            echo "❌ Test summary not found." > summary-tests-results-${{ matrix.node-version }}.log
+  #         grep -E "Test Suites:|Tests:|Snapshots:|Time:" "full-tests-results-${{ matrix.node-version }}.log" > \
+  #           summary-tests-results-${{ matrix.node-version }}.log || \
+  #           echo "❌ Test summary not found." > summary-tests-results-${{ matrix.node-version }}.log
 
-          > "$SUMMARY_ERRORS_FILE"
-          if [ "$exit_code" -ne 0 ]; then
-            grep -iE "(fail|error|unhandled|exception)" "full-tests-results-${{ matrix.node-version }}.log" >> "$SUMMARY_ERRORS_FILE" || true
+  #         > "$SUMMARY_ERRORS_FILE"
+  #         if [ "$exit_code" -ne 0 ]; then
+  #           grep -iE "(fail|error|unhandled|exception)" "full-tests-results-${{ matrix.node-version }}.log" >> "$SUMMARY_ERRORS_FILE" || true
 
-            if [ ! -s "$SUMMARY_ERRORS_FILE" ]; then
-              echo "Tests failed but no detailed error messages found in logs." >> "$SUMMARY_ERRORS_FILE"
-            fi
+  #           if [ ! -s "$SUMMARY_ERRORS_FILE" ]; then
+  #             echo "Tests failed but no detailed error messages found in logs." >> "$SUMMARY_ERRORS_FILE"
+  #           fi
 
-            echo ""
-            echo "❌ Tests are failed. Please check $SUMMARY_ERRORS_FILE."
-            echo ""
-          else
-            echo "✅ All tests passed successfully." > "$SUMMARY_ERRORS_FILE"
-            echo ""
-            echo "✅ All tests are passed successfully."
-            echo ""
-          fi
+  #           echo ""
+  #           echo "❌ Tests are failed. Please check $SUMMARY_ERRORS_FILE."
+  #           echo ""
+  #         else
+  #           echo "✅ All tests passed successfully." > "$SUMMARY_ERRORS_FILE"
+  #           echo ""
+  #           echo "✅ All tests are passed successfully."
+  #           echo ""
+  #         fi
 
-          exit "$exit_code"
+  #         exit "$exit_code"
 
-      - name: Upload Test Logs
-        uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: tests-results-${{ matrix.node-version }}
-          path: |
-            full-tests-results-${{ matrix.node-version }}.log
-            summary-tests-results-${{ matrix.node-version }}.log
-            summary-tests-errors-${{ matrix.node-version }}.log
+  #     - name: Upload Test Logs
+  #       uses: actions/upload-artifact@v4
+  #       if: always()
+  #       with:
+  #         name: tests-results-${{ matrix.node-version }}
+  #         path: |
+  #           full-tests-results-${{ matrix.node-version }}.log
+  #           summary-tests-results-${{ matrix.node-version }}.log
+  #           summary-tests-errors-${{ matrix.node-version }}.log
 
   docker-build:
     name: Build Docker Container
     runs-on: 'ubuntu-latest'
-    needs: [ 'run-lint', 'run-tests' ]
+    # needs: [ 'run-lint', 'run-tests' ]
 
     steps:
       - name: Checkout repository
